version: "3"
services:
  authors:
    build: ./authors
    container_name: authors-service
    ports:
      - 8081:8081
    depends_on:
      - redis
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
  books:
    build: ./books
    container_name: books-service
    ports:
      - 8082:8082
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - 8083:8083
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14269"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - mynet    

networks:
  mynet:
