version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.2.0"
    ports:
      - "5601:5601"

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    volumes:
      - ./logs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
            
  authors:
    build: ./authors
    container_name: authors-service
    ports:
      - 8081:8081
    depends_on:
      - redis
      - jaeger
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
    volumes:
      - ./logs:/home/logs
  books:
    build: ./books
    container_name: books-service
    ports:
      - 8082:8082
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger
    volumes:
      - ./logs:/home/logs
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - 8083:8083
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger
    volumes:
      - ./logs:/home/logs
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - JAEGER_AGENT_HOST=http://jaeger
      - JAEGER_AGENT_PORT=14268
    networks:
      - mynet
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14269"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - mynet    

networks:
  mynet:

volumes:
  elasticsearch_data:
